apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric8
  annotations:
    # when using the proxy 
    # apiserver.base.path: "/_p/oso"
    expose.config.openfact.io/url-key: proxy.pass.url
    #expose.config.openfact.io/host-key: proxy.pass.server
    #expose.config.openfact.io/url-key: apiserver.url
    #expose.config.openfact.io/host-key: apiserver.host
    expose.config.openfact.io/console-url-key: openshift.console.url
    expose.config.openfact.io/apiserver-key: apiserver.host
    expose.config.openfact.io/apiserver-url-key: apiserver.url
    expose-full.service-key.config.openfact.io/keycloak: keycloak.url
    expose-full.service-key.config.openfact.io/sync: sync.api.url
    expose.service-key.config.openfact.io/forge: forge.api.url
    expose.config.openfact.io/apiserver-protocol-key: apiserver.protocol
data:
  apiserver.host: kubernetes
  apiserver.url: http://kubernetes
  apiserver.base.path: ""
  proxy.pass.server: ""
  proxy.pass.url: ""
  apiserver.protocol: http
  keycloak.url: http://keycloak
  forge.api.url: http://generator-backend
  sync.api.url: http://sync
  openshift.console.url: ""
  recommender.api.url: ""
